### ISSUE TITLE
F12后可直接看到付费可见内容

### ISSUE THREAD

**Issue by lyscf** [zxy19/flarum-pay-to-read#1]
![image](https://github.com/zxy19/flarum-pay-to-read/assets/69514837/598a3081-b102-45d6-afc3-2537e4de8063)
请问出现这样的情况是符合预期的吗，在用户没有付费的情况下可以直接F12看到付费可见内容。

**Comment by zxy19** [comment]
应当是不正常的情况。请描述下发现这段代码的位置和触发方式方便排查，谢谢

**Comment by lyscf** [comment]
直接F12 测试环境 Flarum1.8.2  PHP  8.1.17  插件版本 1.1.1
具体位置 如图

**Comment by lyscf** [comment]
![image](https://github.com/zxy19/flarum-pay-to-read/assets/69514837/f6889f0f-1a9d-4dc6-9176-0ab48719106b)

**Comment by zxy19** [comment]
麻烦提供下输入的文章正文原文（没有渲染的原码，包含了pay bbcode的文本）小鱼飘飘-------- 原始邮件 --------发件人： lyscf ***@***.***>日期： 2023年10月4日周三 下午4:42收件人： zxy19/flarum-pay-to-read ***@***.***>抄送： zxy19 ***@***.***>, Comment ***@***.***>主    题： Re: [zxy19/flarum-pay-to-read] F12后可直接看到付费可见内容 (Issue #1)

**Comment by lyscf** [comment]
不好意思，我意识到这是由于CDN缓存导致的误报，非常抱歉！
